// Generated by scripts/catalog.mjs from thinkers.json.
import type { Thought, Source } from './types';
export const cardLoaders: Record<string,()=>Promise<Thought[]>> = {
 'jung': () => import('./library/jung.json').then(module=>module.default as Thought[]),
 'jung-advanced': () => import('./library/jung-advanced.json').then(module=>module.default as Thought[]),
 'nietzsche': () => import('./library/nietzsche.json').then(module=>module.default as Thought[]),
 'freud': () => import('./library/freud.json').then(module=>module.default as Thought[]),
 'frankl': () => import('./library/frankl.json').then(module=>module.default as Thought[]),
 'horney': () => import('./library/horney.json').then(module=>module.default as Thought[]),
 'fromm': () => import('./library/fromm.json').then(module=>module.default as Thought[]),
 'schopenhauer': () => import('./library/schopenhauer.json').then(module=>module.default as Thought[]),
 'weil': () => import('./library/weil.json').then(module=>module.default as Thought[]),
};
export const sourceLoaders: Record<string,()=>Promise<Record<string,Source>>> = {
 'jung': () => import('./library/jung-sources.json').then(module=>module.default),
 'jung-advanced': () => import('./library/jung-advanced-sources.json').then(module=>module.default),
 'nietzsche': () => import('./library/nietzsche-sources.json').then(module=>module.default),
 'freud': () => import('./library/freud-sources.json').then(module=>module.default),
 'frankl': () => import('./library/frankl-sources.json').then(module=>module.default),
 'horney': () => import('./library/horney-sources.json').then(module=>module.default),
 'fromm': () => import('./library/fromm-sources.json').then(module=>module.default),
 'schopenhauer': () => import('./library/schopenhauer-sources.json').then(module=>module.default),
 'weil': () => import('./library/weil-sources.json').then(module=>module.default),
};
