// Optional local QA: install playwright or set THOUGHTFORM_PLAYWRIGHT to its module path.
// Run against a fixed npm run build + npm run preview. Arguments are released thinker file names.
const {chromium}=await import(process.env.THOUGHTFORM_PLAYWRIGHT||'playwright');
import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const root=process.cwd(),out=root+'/artifacts/expansion-review',base=process.env.THOUGHTFORM_REVIEW_URL||'http://localhost:4173';
const files=process.argv.slice(2),all=files.flatMap(file=>JSON.parse(fs.readFileSync(root+'/src/content/library/'+file+'.json')));
const requested=process.env.THOUGHTFORM_REVIEW_IDS?.split(',').filter(Boolean),cards=requested?all.filter(card=>requested.includes(card.id)):all;
if(requested)assert(cards.length===new Set(requested).size,'unknown or duplicate requested card');fs.mkdirSync(out,{recursive:true});
const build=crypto.createHash('sha256').update(fs.readFileSync(root+'/dist/index.html')).digest('hex');
const browser=await chromium.launch({executablePath:process.env.THOUGHTFORM_BROWSER||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});const report=[],errors=[];let cursor=0;
async function settle(page,card,i){await page.waitForFunction(({caption,i})=>{const el=document.querySelector('.lesson-illustration');return el?.getAttribute('data-lesson-beat')===String(i)&&el.querySelector('.lesson-reading p')?.textContent===caption;},{caption:card.scene.lesson.beats[i].caption,i});await page.waitForTimeout(1500);}
async function record(page){await page.evaluate(()=>{window.auditSamples=[];window.auditRecording=true;const frame=()=>{if(!window.auditRecording)return;window.auditSamples.push({t:performance.now(),y:scrollY,height:document.documentElement.scrollHeight,open:document.querySelector('.depth-link')?.getAttribute('aria-expanded')});requestAnimationFrame(frame);};frame();});}
async function samples(page){return await page.evaluate(()=>{window.auditRecording=false;return window.auditSamples;});}
async function worker(){const context=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'no-preference'});await context.addInitScript(()=>{localStorage.setItem('thoughtform.reading-guide.seen','true');localStorage.setItem('thoughtform.v1',JSON.stringify({paused:true,animationSpeed:1}));});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));while(cursor<cards.length){const card=cards[cursor++],dir=out+'/'+card.thinker;fs.mkdirSync(dir,{recursive:true});const item={id:card.id,thinker:card.thinker,title:card.title,build,beats:[],clipping:[],collisions:[],mobile:[],scroll:{}};try{
 await page.setViewportSize({width:390,height:900});await page.goto(base+'/#'+card.id);await page.waitForSelector('[data-thought-id="'+card.id+'"]');await settle(page,card,0);await page.screenshot({path:dir+'/'+card.id+'-phone.png'});
 for(let i=0;i<card.scene.lesson.beats.length;i++){if(i){await page.locator('.lesson-illustration').press('ArrowRight');await settle(page,card,i);}const name=dir+'/'+card.id+'-beat-'+i+'.png';await page.locator('.lesson-illustration').screenshot({path:name});const measures=await page.locator('.lesson-illustration > svg').evaluate(svg=>{const labels=[...svg.querySelectorAll('text')].filter(el=>+getComputedStyle(el).opacity>.95).map(el=>{const box=el.getBoundingClientRect(),svgBox=svg.getBoundingClientRect();return {text:el.textContent,x:box.x-svgBox.x,y:box.y-svgBox.y,width:box.width,height:box.height,svgWidth:svgBox.width,svgHeight:svgBox.height};});return labels;});const clipped=measures.filter(l=>l.x<-.5||l.y<-.5||l.x+l.width>l.svgWidth+.5||l.y+l.height>l.svgHeight+.5);item.clipping.push(...clipped.map(label=>({beat:i,...label})));for(let j=0;j<measures.length;j++)for(let k=j+1;k<measures.length;k++){const a=measures[j],z=measures[k];if(a.x<z.x+z.width-2&&a.x+a.width>z.x+2&&a.y<z.y+z.height-2&&a.y+a.height>z.y+2)item.collisions.push({beat:i,a:a.text,b:z.text});}item.beats.push({caption:card.scene.lesson.beats[i].caption,screenshot:name});}
 // Real visible card tap first; no automatic scroll into view can mask its origin.
 await page.evaluate(()=>scrollTo(0,0));const st=await page.locator('.statement').boundingBox();assert(st&&st.y>0&&st.y+Math.min(st.height/2,20)<900,'statement should be visible');await record(page);await page.mouse.click(st.x+st.width/2,st.y+Math.min(st.height/2,20));await page.waitForTimeout(1300);item.scroll.expand=await samples(page);assert(item.scroll.expand.every((s,i,list)=>i===0||s.y>=list[i-1].y-2),'expansion scroll reverses');assert(await page.locator('.depth-link').getAttribute('aria-expanded')==='true');assert(await page.locator('.reading-paragraph').count()===3);assert(await page.locator('.margin-drawing').count()===2);assert(await page.locator('.source-list a').count()===card.sources.length,'all source links available');
 for(let i=0;i<2;i++){const drawing=page.locator('.margin-drawing').nth(i);await drawing.scrollIntoViewIfNeeded();await page.waitForTimeout(100);await drawing.screenshot({path:dir+'/'+card.id+'-reading-'+i+'.png'});const clipped=await drawing.locator('svg').evaluate(svg=>{const area=svg.getBoundingClientRect();return [...svg.querySelectorAll('text')].map(el=>({text:el.textContent,r:el.getBoundingClientRect()})).filter(({r})=>r.left<area.left-.5||r.right>area.right+.5||r.top<area.top-.5||r.bottom>area.bottom+.5).map(({text})=>text);});item.clipping.push(...clipped.map(text=>({drawing:i,text})));}
 const p3=page.locator('.nuance').nth(2);await p3.scrollIntoViewIfNeeded();const r=await p3.boundingBox();const initialY=await page.evaluate(()=>scrollY);await record(page);await page.mouse.click(r.x+r.width*.5,Math.min(840,Math.max(40,r.y+30)));await page.waitForTimeout(1100);item.scroll.collapse=await samples(page);assert(item.scroll.collapse.every((s,i,list)=>i===0||s.y<=list[i-1].y+2),'collapse scroll reverses');assert(await page.locator('.depth-link').getAttribute('aria-expanded')==='false');assert(await page.evaluate(()=>scrollY)<2);assert(item.scroll.collapse.some(s=>s.y>initialY*.3&&s.open==='true'),'content retained while scrolling up');
 for(const width of [320,360,390,430]){await page.setViewportSize({width,height:900});await page.waitForTimeout(100);const layout=await page.evaluate(()=>({width:innerWidth,body:document.documentElement.scrollWidth,title:document.querySelector('h1')?.textContent}));assert(layout.body<=width+1,'horizontal overflow '+width);await page.screenshot({path:dir+'/'+card.id+'-mobile-'+width+'.png'});item.mobile.push(layout);}
 assert(item.clipping.length===0,'clipped drawing labels');item.ok=true;
 }catch(e){item.ok=false;item.error=e.stack;console.log('FAIL',card.id,e.message);}report.push(item);console.log('Reviewed',report.length+'/'+cards.length,card.id,'clip',item.clipping.length,'overlap',item.collisions.length);fs.writeFileSync(out+'/report-'+files.join('-')+(requested?'-'+crypto.createHash('sha256').update(requested.join(',')).digest('hex').slice(0,8):'')+'.json',JSON.stringify({build,cards:report,errors},null,2));}await context.close();}
await Promise.all(Array.from({length:4},worker));assert(build===crypto.createHash('sha256').update(fs.readFileSync(root+'/dist/index.html')).digest('hex'),'build changed during capture');await browser.close();console.log('DONE',cards.length,'errors',errors.length,'failed',report.filter(r=>!r.ok).length);if(report.some(r=>!r.ok)||errors.length)process.exitCode=1;
