import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../src/content/', import.meta.url);
const items = [], sources = {}, cards = JSON.parse(await readFile(new URL('opening.json', root), 'utf8'));
const registry = JSON.parse(await readFile(new URL('thinkers.json', root), 'utf8'));
const thinkerIds=new Set(registry.map(t=>t.id));
if(thinkerIds.size!==registry.length)throw new Error('Duplicate thinker in release registry');
const filenames = registry.flatMap(thinker => thinker.files.flatMap(file => [`${file}-sources.json`, `${file}.json`]));
for (const filename of filenames) {
 const data=JSON.parse(await readFile(new URL(`library/${filename}`,root),'utf8'));
 if(filename.endsWith('-sources.json'))Object.assign(sources,data);
 else for(const card of data) {
  cards.push(card);
  items.push({id:card.id,thinker:card.thinker,collection:card.collection,concept:card.concept,title:card.title,tags:card.tags,depth:card.depth});
 }
}
const ids = new Set();
function checkActors(actors, location) {
 const siblings = new Set();
 for(const actor of actors) {
  if(!actor || typeof actor !== 'object' || !['path','circle','figure','text','group'].includes(actor.type))throw new Error(`${location}: invalid drawing actor`);
  if(!actor.id || siblings.has(actor.id))throw new Error(`${location}: missing or duplicate actor ID ${actor.id}`);
  siblings.add(actor.id);
  if(actor.type === 'group')checkActors(actor.children || [], `${location}/${actor.id}`);
 }
}
for(const card of cards) {
 if(!card.id || ids.has(card.id))throw new Error(`Missing or duplicate thought ID: ${card.id}`);
 ids.add(card.id);
 if(card.nuance?.split(/\n\s*\n/).length !== 3 || card.readingArt?.length !== 2)throw new Error(`${card.id}: expected three reading paragraphs and two explanatory drawings`);
 const beats=card.scene?.lesson?.beats;
 if(!beats || beats.length < 3)throw new Error(`${card.id}: expected a staged teaching lesson with at least three beats`);
 if(!registry.some(t=>t.id===card.thinker))throw new Error(`${card.id}: unknown thinker`);
 if(!card.reflection || !card.title || !card.statement || !card.explanation)throw new Error(`${card.id}: incomplete reading`);
 if(card.nuance.includes(card.explanation))throw new Error(`${card.id}: opening explanation repeated in expanded reading`);
 for(const source of card.sources || [])if(!sources[source] && !['shadow','psyche','complex','self','individuation','dreams','transcendent','types','archetypes','imagination'].includes(source))throw new Error(`${card.id}: unavailable source ${source}`);
 beats.forEach((beat, i) => {
  if(!beat.caption || !Array.isArray(beat.actors))throw new Error(`${card.id}, beat ${i}: missing teaching caption or drawing`);
  checkActors(beat.actors, `${card.id}, beat ${i}`);
 });
 card.readingArt.forEach((drawing, i) => checkActors(drawing.actors, `${card.id}, reading drawing ${i}`));
}
for(const card of cards)for(const related of card.related || [])if(!ids.has(related))throw new Error(`${card.id}: unavailable related thought ${related}`);
for(const thinker of registry){
 const authored=cards.filter(card=>card.thinker===thinker.id);
 if(authored.length<20)throw new Error(`${thinker.id}: a released thinker needs at least twenty complete thoughts`);
 const titles=new Set(authored.map(card=>card.title.toLowerCase()));
 if(titles.size!==authored.length)throw new Error(`${thinker.id}: repeated thought title`);
 const orders=new Set();
 for(const card of authored)if(card.sequence){const key=`${card.sequence.id}:${card.sequence.order}`;if(orders.has(key))throw new Error(`${card.id}: duplicate order in sequence`);orders.add(key);}
}
await writeFile(new URL('catalog.json',root),JSON.stringify(items,null,2)+'\n');
await writeFile(new URL('source-library.json',root),JSON.stringify(sources,null,2)+'\n');
// Generate only released imports. Adding a batch to the registry updates both
// the reading index and lazy loaders; unpublished research stays out of the build.
const files=registry.flatMap(thinker=>thinker.files);
await writeFile(new URL('loaders.ts',root),`// Generated by scripts/catalog.mjs from thinkers.json.\nimport type { Thought, Source } from './types';\nexport const cardLoaders: Record<string,()=>Promise<Thought[]>> = {\n${files.map(file=>` '${file}': () => import('./library/${file}.json').then(module=>module.default as Thought[]),`).join('\n')}\n};\nexport const sourceLoaders: Record<string,()=>Promise<Record<string,Source>>> = {\n${files.map(file=>` '${file}': () => import('./library/${file}-sources.json').then(module=>module.default),`).join('\n')}\n};\n`);
console.log(`Validated ${cards.length} unique thoughts; indexed ${items.length} additional thoughts across ${new Set(items.map(c=>c.thinker)).size} thinkers.`);
