import { useEffect, useState } from 'react';
import { cards } from './content/cards';
import { sources } from './content/sources';
import { CardStack } from './components/CardStack';
import { Icon } from './components/Icons';
const KEY='inner-index.v1';
function readState(){try{return JSON.parse(localStorage.getItem(KEY)||'{}');}catch{return {};}}
const initial=readState();
export default function App(){
 const [index,setIndex]=useState(Math.max(0,cards.findIndex(c=>c.id===initial.current)));
 const [bookmarks,setBookmarks]=useState<string[]>(Array.isArray(initial.bookmarks)?initial.bookmarks:[]);
 const [viewed,setViewed]=useState<string[]>(Array.isArray(initial.viewed)?initial.viewed:[]);
 const [panel,setPanel]=useState<'detail'|'index'|null>(null); const [paused,setPaused]=useState(false);
 const card=cards[index];
 function move(direction:number){setIndex(i=>Math.max(0,Math.min(cards.length-1,i+direction)));}
 useEffect(()=>{setViewed(v=>v.includes(card.id)?v:[...v,card.id]);},[card.id]);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify({current:card.id,bookmarks,viewed}));}catch{}},[card.id,bookmarks,viewed]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.key==='Escape')setPanel(null);if(panel|| (e.target as HTMLElement).matches('input,textarea'))return;if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[panel]);
 function save(){setBookmarks(b=>b.includes(card.id)?b.filter(id=>id!==card.id):[...b,card.id]);}
 return <div className={`app ${paused?'paused':''}`}><header className="site-header"><a className="wordmark" href="/" onClick={e=>e.preventDefault()} aria-label="Inner Index home"><span className="monogram">ıı</span><span>inner index<span className="wordmark-dot">.</span></span></a><span className="header-note">A FIELD GUIDE TO THE INNER WORLD</span><button className="library-button" onClick={()=>setPanel('index')}><span>The index</span><Icon name="index" size={18}/></button></header>
 <main><div className="reading-label"><span className="live-dot"/>THE JUNG COLLECTION <span className="label-rule"/><span>{String(index+1).padStart(2,'0')} / {String(cards.length).padStart(2,'0')}</span></div><div className="reading-stage"><button className="side-nav previous" aria-label="Previous thought" onClick={()=>move(-1)} disabled={index===0}><Icon name="arrow-left"/></button><CardStack key={card.id} card={card} next={cards[Math.min(index+1,cards.length-1)]} index={index} total={cards.length} saved={bookmarks.includes(card.id)} onSave={save} onMove={move} onDetails={()=>setPanel('detail')}/><button className="side-nav next" aria-label="Next thought" onClick={()=>move(1)} disabled={index===cards.length-1}><Icon name="arrow-right"/></button></div>
 <nav className="flow-nav" aria-label="Thought navigation"><button onClick={()=>move(-1)} disabled={index===0} aria-label="Previous thought"><Icon name="arrow-left" size={18}/></button><span className="swipe-hint">{index===cards.length-1?'A place to pause.':'Swipe. Let a thought stay.'}</span><button onClick={()=>move(1)} disabled={index===cards.length-1} aria-label="Next thought"><Icon name="arrow-right" size={18}/></button></nav><div className="progress-track" role="progressbar" aria-label="Position in collection" aria-valuemin={1} aria-valuemax={cards.length} aria-valuenow={index+1}><span style={{width:`${((index+1)/cards.length)*100}%`}}/></div>
 </main><footer className="site-footer"><span>Difficult ideas. Slowly understood.</span><button className="motion-control" onClick={()=>setPaused(p=>!p)} aria-label={paused?'Play illustrations':'Pause illustrations'}><Icon name={paused?'play':'pause'} size={13}/><span>{paused?'Resume motion':'A little stillness'}</span></button><span className="footer-edition">VOLUME 01 <span>·</span> CARL JUNG</span></footer>
 {panel && <div className="panel-backdrop" onClick={()=>setPanel(null)}><section className="detail-panel" role="dialog" aria-modal="true" aria-labelledby="panel-title" onClick={e=>e.stopPropagation()}><div className="panel-top"><span className="eyebrow">{panel==='detail'?'A closer reading':'The collection'}</span><button className="icon-button" onClick={()=>setPanel(null)} aria-label="Close panel" autoFocus><Icon name="close"/></button></div><h2 id="panel-title">{panel==='detail'?card.title:'The inner life'}</h2>{panel==='detail'?<><p>{card.nuance}</p>{card.reflection&&<div className="reflection"><span className="eyebrow">A question to sit with</span><p>{card.reflection}</p></div>}<div className="source-list"><span className="eyebrow">Reading behind this thought</span>{card.sources.map(id=>sources[id]&&<a key={id} href={sources[id].url} target="_blank" rel="noreferrer"><span>{sources[id].author} · {sources[id].title} ↗</span><small>{sources[id].reference}</small><small>Read an institutional introduction</small></a>)}<small className="paraphrase-note">Original paraphrase, not a quotation. Jung’s model is a way of interpreting psychic life.</small></div></>:<><p className="index-intro">One idea leads to another. Begin anywhere.</p><div className="index-list">{cards.map((c,i)=><button key={c.id} className={i===index?'current':''} onClick={()=>{setIndex(i);setPanel(null);}}><span className="index-number">{String(i+1).padStart(2,'0')}</span><span>{c.title}<small>{c.concept}</small></span><span className="index-marker">{bookmarks.includes(c.id)?'◇':viewed.includes(c.id)?'·':''}</span></button>)}</div></>}</section></div>}
 <div className="sr-only" aria-live="polite">Thought {index+1} of {cards.length}: {card.title}</div></div>;
}
